### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by faded-TJU** [tobyperrett/trx#5]
Thanks a lot for making your code public. I am trying to replicate your results on SSv2 and HMDB51. This was my first foray into video action recognition. Some problems happen when i work with datasets. 
    1. I get SSv2 from TwentyBN  https://20bn.com/datasets/download, but when i use cat 20bn-something-something-v2-?? | tar zx, it brings a mistake:
        localhost dataset]$ cat 20bn-something-something-v2-?? | tar zx
        gzip: stdin: not in gzip format
        tar: Child died with signal 13
        tar: Error is not recoverable: exiting now
    2. As you said, "Download your chosen dataset, and extract frames to be of the form dataset/class/video/frame-number.jpg", does this mean that I should put all the extracted frames into the ZIP file ? (args.path = os.path.join(args.scratch, "video_datasets/data/hmdb51.zip") or this zip file should consist of all the videos ? 
    3. How can i decompose the video into frames? I cannot see the way ARN dealt with.
    It would be greatly appreciated.
Best wishes!

**Comment by tobyperrett** [comment]
1. No idea. I just followed the instructions and didn't have a problem. Maybe check the downloads of all the parts finished correctly.
2. All the extracted frames are in the zip file, not the original videos.
3. Use ffmpeg (this is an essential program if you're going to be using videos).

I might still have things zipped up that you're after, so send me your email address in a private message and I'll see if I can send something over.

**Comment by faded-TJU** [comment]
Thank you so much for your response!! @tobyperrett.

**Comment by tobyperrett** [comment]
No problem @faded-TJU . Not actually sure if github lets you send private messages, but you'll find my email address in the paper if you'd like some zip files.

**Comment by faded-TJU** [comment]
I'm not sure about your email address.
Can you send it to this address: 2033009@tongji.edu.cn , if you have things zipped.
Thanks!

**Comment by faded-TJU** [comment]
Thank you so much for your kind reply! I will check the downloads of all the parts finished correctly again.
Can you send to this email if you have things zipped up?  2033009@tongji.edu.cn
Best wishes to you!

**Comment by zzzhhh1031** [comment]
> No problem @faded-TJU . Not actually sure if github lets you send private messages, but you'll find my email address in the paper if you'd like some zip files.

Thank you for your excellent work, I would like to get hmdb51_256q5.zip of the compressed package, can you provide me thanks

**Comment by IemProg** [comment]
@faded-TJU Could you please, share with us how you solved the issue of SSv2 dataset ?
I'm getting the same error, can't unzip the files after downloading them.

**Comment by IemProg** [comment]
The solutions is: 

To extract the videos, follow the following procedure

   1. unzip 20bn-something-something-v2-\??.zip
   2. cat 20bn-something-something-v2-?? | tar -xvzf -
