### ISSUE TITLE
Change num_gpus

### ISSUE THREAD

**Issue by faded-TJU** [tobyperrett/trx#7]
Thank you very much for your help on the datasets!
Can I run it on two 3090ti GPUs(24GB)? I changed args.num_gpus and args.num_workers to 2, 1 respectively in run.py, but it failed. Did I miss anything else?

`I RUN THIS :python run.py -c checkpoint_dir --query_per_class 4 --shot 5 --way 5 --trans_linear_out_dim 1152 --tasks_per_batch 16 --test_iters 75000 --dataset ssv2 --split 3 -lr 0.001 --method resnet50 --img_size 224`

`Options: Namespace(checkpoint_dir='checkpoint_dir', dataset='ssv2', debug_loader=False, img_size=224, learning_rate=0.001, method='resnet50', num_gpus=2, num_test_tasks=10000, num_workers=1, opt='sgd',`

/trx-main/model.py", line 94, in forward
    class_k = torch.index_select(mh_support_set_ks, 0, self._extract_class_indices(support_labels, c))
**_RuntimeError: Input, output and indices must be on the current device_**

Best wishes,
Han

**Comment by PHDJieFu** [comment]
Maybe I can solve your problem. You can communicate with me through the Wechat. My ID is fj_snbc

**Comment by faded-TJU** [comment]
> Maybe I can solve your problem. You can communicate with me through the Wechat. My ID is fj_snbc

Okay, thanks! I will communicate with you soon. My ID is Wanghannnnnn.thx :)

**Comment by Anirudh257** [comment]
@faded-TJU You can do .to(device) before line 94. It will explicitly shift all tensors to 1 device.

**Comment by faded-TJU** [comment]
> @faded-TJU You can do .to(device) before line 94. It will explicitly shift all tensors to 1 device.

Thanks！I will try it.

**Comment by tobyperrett** [comment]
You should be able to get it working on your setup as you have more total gpu memory than me.  You'll need to modify the distribute function as discussed in the readme.  I leave the transformer on gpu 0, but your error seems to indicate that the transformer isn't on that gpu.  It should be an easy fix though, especially with such a clear error message.

**Comment by aniket004** [comment]
I am getting the same issue. 
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:6!
Any idea how to fix this? Thanks in advance!

**Comment by Anirudh257** [comment]
@aniket004 Can you try doing *.to(device)* before line 94 once.

**Comment by aniket004** [comment]
@Anirudh257 I have tried that, still no luck! Did it worked out for you?

**Comment by tobyperrett** [comment]
Looks like you've got a machine with more than 4 gpus. I only have 4. You'll need to change the distribute function like it says in the readme, and check for .cuda() function calls to check they're putting things on the right device. Or you could just export 4 gpus in your bash environment before running, as it looks like you've got some things on number 6.  E.g. export CUDA_VISIBLE_DEVICES=0,1,2,3

**Comment by Anirudh257** [comment]
@aniket004, as Toby mentioned, I also have a machine of 4 GPUs and it worked without any issue for me.

**Comment by aniket004** [comment]
Hi @Anirudh257 , can you specify which line in which file are you mentioning?

**Comment by Anirudh257** [comment]
https://github.com/tobyperrett/trx/issues/7#issuecomment-869581370
@aniket004
