### ISSUE TITLE
about query_per_class, query_per_test 

### ISSUE THREAD

**Issue by ycbilge** [tobyperrett/trx#8]
Thanks for the code again. When you are are changing the parameters for lets say 20-way 1-shot are you changing the parameters of _query_per_class_, _query_per_test_? Or should we just change _--way_ and _--shot_ parameters and leave the others as default?
changing;
parser.add_argument("--way", type=int, default=5, help="Way of each task.") -> 20
parser.add_argument("--shot", type=int, default=5, help="Shots per class.") -> 1
not changing;
parser.add_argument("--query_per_class", type=int, default=5, help="Target samples (i.e. queries) per class used for training.")
parser.add_argument("--query_per_class_test", type=int, default=1, help="Target samples (i.e. queries) per class used for testing.")
Thanks for your help!

**Comment by tobyperrett** [comment]
Hi.  You'd set --way 20 and --shot 1.  The number of queries per class will affect training speed (by getting a better batch score using more queries), but uses more memory.  You might have to select a value lower than 5 for it to fit on your GPU.
